apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: postgresql-daily-backup
spec:
  schedule: "@daily"
  template:
    includedNamespaces:
      - postgresql
    labelSelector:
      matchLabels:
        app: postgresql

