apiVersion: batch/v1
kind: Job
metadata:
  name: create-minio-bucket
  namespace: minio
spec:
  template:
    spec:
      containers:
      - name: minio-client
        image: minio/mc
        command: 
        - /bin/sh
        - -c
        - |
          mc alias set myminio http://minio.minio.svc.cluster.local:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD && 
          mc mb myminio/velero
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: root-user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: root-password
      restartPolicy: Never
